### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by tamorim** [vtex-apps/theme#104]
@dfosco See how it conflicts! (the styles applied should be of FilterButton)

![image](https://cloud.githubusercontent.com/assets/5040487/11484351/bd3628bc-9794-11e5-9393-63deb5bf74f4.png)

![image](https://cloud.githubusercontent.com/assets/5040487/11484419/0b6c80b2-9795-11e5-99da-f9253a80a939.png)

**Comment by dfosco** [comment]
@tamorim Ok, time to face this monster... I'm re-adopting BEM across **all apps**. Get ready for `feature/css-refactor` branches everywhere!

**Comment by dfosco** [comment]
@tamorim Done! Changes listed under [#108](https://github.com/vtex-apps/theme/pull/108).

pls review, migo :relieved:
