### ISSUE TITLE
Remove unnecessary classes once FilterPanel CSS refactor merges with master

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/theme#105]
These classes on `CategoryHeader.less` need to be changed/removed, but currently break the layout because upstream changes on `FilterPanel` haven't been merged yet.

![image](https://cloud.githubusercontent.com/assets/3229933/11516163/de587dcc-9868-11e5-9026-5767f151591d.png)

**Comment by brenoc** [comment]
@dfosco What's the status here?

**Comment by dfosco** [comment]
@brenoc Done, will be closed when #124 is merged

**Comment by dfosco** [comment]
@brenoc @tamorim Please review :)
