### ISSUE TITLE
[product-page] Add product image caroussel

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/theme#20]

**Comment by brenoc** [comment]
Reference: https://github.com/akiran/react-slick
Demo: http://webrafter.com/opensource/react-slick

**Comment by dfosco** [comment]
@brenoc This is being done in one of the branches from the hackathon — maybe @leandrooriente and @gugiserman could start working on this one next Friday?

**Comment by tamorim** [comment]
Done one `product-image` component.
