### ISSUE TITLE
Image Upload on BannerEditor

### ISSUE THREAD

**Issue by brenoc** [vtex-apps/theme#35]
Use Thumbor for this:
https://github.com/thumbor/thumbor/wiki/How-to-upload-images#upload-an-image-via-the-rest-api

**Comment by brenoc** [comment]
Sendo feito em: https://github.com/vtex-apps/storefront-theme/tree/feature/imageUpload

**Comment by dfosco** [comment]
How's progress on this feature, @brenoc?

**Comment by brenoc** [comment]
I think it's best for us to wait the implementation of the Storefront proxy.

cc @amoreira @felipecastrosm

**Comment by brenoc** [comment]
Moved to https://github.com/vtex-apps/banner/issues/10
