### ISSUE TITLE
Prototype for Filter Selection panel

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/theme#45]

**Comment by dfosco** [comment]
<img width="320" alt="screen shot 2015-10-08 at 3 56 50 pm" src="https://cloud.githubusercontent.com/assets/3229933/10376930/e05e488e-6dd6-11e5-99b4-29e10fc28ada.png">

Layout for filter selection panel is done. Still pending:

 - [ ] Animation for accordion showing/hiding extra results

**Comment by dfosco** [comment]
@tamorim Let's further discuss the changes in React's animation tomorrow so we can close this :relieved:

**Comment by tamorim** [comment]
@dfosco I don't think that the accordion is necessary, but I still have to make the `See all brands` >:

**Comment by dfosco** [comment]
@tamorim Can't you pull them from the facets and do a simple show/hide? I'll implement a better interaction later.

**Comment by tamorim** [comment]
@dfosco Don't understand if you're referring to the accordion or the link

**Comment by dfosco** [comment]
@tamorim The link! Just show the data and I'll improve the interaction next week :)

**Comment by tamorim** [comment]
@dfosco Okidoki

**Comment by brenoc** [comment]
Done here https://github.com/vtex-apps/filter-panel
