### ISSUE TITLE
Category sidepanel allows scrolling of component in the background

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/theme#50]

**Comment by dfosco** [comment]
@tamorim @brenoc @bellacorbo @amoreira We need to tell `CategoryPage` to change to `overflow:hidden` when any panel is instantiated above it.

It seems to me that every panel should load inside the same `SidePanel` wrapper — seems to be the easiest way to make it happen. 

Right now there's a bunch of different `Panels` in the category component (not to mention `EditorPanel` and such), but this behavior is pretty much universal with the Storefront — if you have a panel taking 100% of the screen the components beneath it should not scroll.

Ideas?

**Comment by brenoc** [comment]
@dfosco I dont see a problem with scrolling, really, this won't bother the user.

About the `SidePanel` being the same, I agree it should be the same React component. It should be used like so:

```js
<SidePanel abc="oi">
  <ComponentWithContent/>
</SidePanel>
```

**Comment by brenoc** [comment]
Or even:

```js
<SidePanel abc="oi">
  <div>
    <h1>Hello</h1>
  </div>
</SidePanel>
```

**Comment by tamorim** [comment]
@brenoc I'm not sure about won't bothering the user...
If you're scrolling a long list of products and then use some menu that takes the screen, even partially, is to expected that you won't lose your position.

Using me as example, I get REALLY annoyed when that happens.

**Comment by tamorim** [comment]
@dfosco I agree with a universal Sidebar component too.

**Comment by dfosco** [comment]
@tamorim nailed the example.

and +1 for a universal `Sidebar` component, it will make prototyping MUCH EASIER as well.

**Comment by brenoc** [comment]
@tamorim really? open http://walmartv5.vtexcommercebeta.com.br/admin/checkout/#/orders?orderBy=creationDate,desc and click on the filter, see if this behaviour really bothers

**Comment by tamorim** [comment]
@brenoc Yep, it annoys. On Desktop less so, because it's easier to scroll fast,  but on phone it's mind wrecking, specially on long lists.

Besides it isn't a natural behaviour.

**Comment by tamorim** [comment]
@brenoc OMG, tested on phone now, it's horrible.

**Comment by dfosco** [comment]
@brenoc Yeah, it's pretty bad — I think there should be no interaction whatsoever with the background when you have a fullscreen panel open, almost as if the component in the background wasn't rendered while the panel is there.

**Comment by brenoc** [comment]
@dfosco @tamorim okok, I agree with you

**Comment by tamorim** [comment]
Fixed.

**Comment by brenoc** [comment]
@tamorim can you mention the commit?

**Comment by tamorim** [comment]
Here: vtex-apps/theme@71ff9b5825b875d4bf1492409cd0e66d84c1e2a2
