### ISSUE TITLE
Components with multiple variants

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/theme#54]
Yesterday I added a variation to one of our `PanelNav` component that changes the style applied when a given prop changes:

<img width="322" alt="screen shot 2015-10-08 at 8 37 51 pm" src="https://cloud.githubusercontent.com/assets/3229933/10397777/ccc74cea-6e7f-11e5-8fcd-c1e54905fc7f.png">
<img width="323" alt="screen shot 2015-10-08 at 8 37 42 pm" src="https://cloud.githubusercontent.com/assets/3229933/10397695/64864992-6e7f-11e5-8956-a7ef02ea46d6.png">

It works fine for our current purpose, although it only changes CSS. If I wanted variants with different component structure, I'd need another solution.

What's our current approach for this? I figure this is also the first step before allowing the end-user to change the component style from the editor — @bellacorbo and @bernardolemgruber, how are you approaching the multiple styles for the SKU Selector?

Last, but not least, we need to document the different variations and which props devs should use to access them!

**Comment by bellacorbo** [comment]
@dfosco We are yet to implement other styles for the Sku Selector. This is actually our next step: this and managing how these different styles and components will be changed via editor.

**Comment by dfosco** [comment]
@bellacorbo Cool, let's keep this thread going to discuss the best way to do it!

**Comment by brenoc** [comment]
@dfosco You may use React in our favor, like this:

Default panel header:
```js
<PanelNav>
   <h1>Ordernar por</h1>
   <ListWhatever items={items}/>
</PanelNav>
```

Custom panel header:
```js
<PanelNav header={MyHeader}>
   <h1>Ordernar por</h1>
   <ListWhatever items={items}/>
</PanelNav>
```

**Comment by brenoc** [comment]
Closing this issue. You may move it to https://github.com/vtex-apps/filter-panel

**Comment by dfosco** [comment]
@brenoc Fine by me, this should become a feature in the editor for this component, not an issue in itself.
