### ISSUE TITLE
Pagination? Let's discuss

### ISSUE THREAD

**Issue by tamorim** [vtex-apps/theme#62]

**Comment by tamorim** [comment]
@dfosco

**Comment by dfosco** [comment]
@tamorim

**Comment by dfosco** [comment]
:page_facing_up:

**Comment by dfosco** [comment]
All right, just kidding. I probably won't be able to tackle it this week (maaaaaybe Friday night?)

Please remember to bug me next week if you don't have a prototype by then :smile:

**Comment by tamorim** [comment]
I'll mark this as done, since I've made the `LoadMore` style.
Other navigations can be done on other iterations!
