### ISSUE TITLE
Move SkuSelector to its own repo

### ISSUE THREAD

**Issue by bellacorbo** [vtex-apps/theme#69]
In our current project structure, the SkuSelector and its other children components are a part of the Product directory. I think it makes more sense for the SkuSelector to have a directory of its own, and consequently, for the SkuSelectorEditor to be also structured separately (I think it is too big of a component to be defined and structured inside Product). Still, part of the logic and the state definitions necessary for the selection of skus are in the file Product.js (because they are properties of the product itself), and therefore they're still together. @brenoc @tamorim @dfosco @bernardolemgruber What do you think is the best solution?

**Comment by dfosco** [comment]
@bellacorbo Conceptually speaking, the `SkuSelector` should have its own structure — not only it's a complex component, it's an optional feature for the product page that not every store will use, so it makes sense to have it separated.

If there are technical limitations that make it hard to separate the component, those should be refactored — ideally, these limitations should not get in the way of sensible architecture.

What do you think?

**Comment by tamorim** [comment]
Well, I think that you can abstract what the SkuSelector needs and make the props that it will use as a form of "contract".
Anyone who will use the component should be aware of what it expects in order to work properly.

**Comment by brenoc** [comment]
I agree with @tamorim. SkuSelector `props` it's its API. Make this API slim and easy to use and you're good to go (to move it away from the Product directory).

**Comment by bellacorbo** [comment]
Ok, guys. Thanks for your help!

**Comment by brenoc** [comment]
@bellacorbo now you're supposed to move SkuSelector to a separate app and repo, just like [Banner](/vtex-apps/storefront-banner) and [Shelf](/vtex-apps/storefront-shelf).

**Comment by bellacorbo** [comment]
Will wait for #103 to be merged.

**Comment by brenoc** [comment]
Done https://github.com/vtex-apps/sku-selector
