### ISSUE TITLE
Cleanup old branches

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/theme#74]
@brenoc Could you do this spring cleaning? You're the most knowledgeable about most branches, but let us know if there's anything you're unsure about.

I'm not even sure we should do this right now because of the hackathon branches — are we going to spin them off into their own repositories?

**Comment by brenoc** [comment]
> I'm not even sure we should do this right now because of the hackathon branches — are we going to spin them off into their own repositories?
@dfosco propably yes

I'll just delete the stale branches

**Comment by dfosco** [comment]
:ok_hand:

**Comment by tamorim** [comment]
Done!
