### ISSUE TITLE
Unavailable SKU variations are selectable

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/theme#79]
Even though we lock the button selection through CSS, we are using a custom event listener (`onTouchTap`) to record the tap, so it still makes it selectable.

**Comment by dfosco** [comment]
@bellacorbo Strangely enough, this only happens when changing the data attribute `data-is-available` through the inspector — when you have one option selected it will make the other unavailable and unselectable.

I'm not sure it will work properly when the catalog says the variation is unavailable though, so we should at least test it.

**Comment by bellacorbo** [comment]
@dfosco When I first implemented the sku selector, I made sure it would work by getting the catalog's availabilities for each variation and resolving the interaction between selected and unselected variations. 

That is why the variation's availability (depending to the context in which the is in: whether he has already selected a variation or not) is what sets the buttons to selectable or not. The data attributes were introduced later in the components history, and when you change only the attribute, it is not enough to set the button as unselectable (you need the availability).
